FROM python:3.12-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_DISABLE_PIP_VERSION_CHECK=1 \
    PIP_DEFAULT_TIMEOUT=1000 \
    PIP_RETRIES=10

WORKDIR /app
COPY requirements-supervisor.txt .
RUN pip install --no-cache-dir -r requirements-supervisor.txt
COPY models.py telemetry.py supervisor.py ./
CMD ["python", "supervisor.py"]
