version: '3.8'
services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: lexguard-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: lexguard
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: lexguard-rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data: